<?php

namespace Rindra\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UtilisateurAdresseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurAdresseRepository extends EntityRepository
{
}
