rindra_notification:
    path:     /notifications
    defaults: { _controller: RindraNotificationBundle:Message:index }

rindra_notificatio_create:
    path:     /notification/create
    defaults: { _controller: RindraNotificationBundle:Message:create }

rindra_notification_edit:
    path:     /notification/edit/{id}
    defaults: { _controller: RindraNotificationBundle:Message:create }
